typo3

diff --git a/.github/workflows/chroma-release.yml b/.github/workflows/chroma-release.yml
--- a/.github/workflows/chroma-release.yml
+++ b/.github/workflows/chroma-release.yml
@@ -29,12 +29,6 @@ jobs:
       uses: actions/setup-python@v4
       with:
         python-version: '3.10'
-    # - name: Install Client Dev Dependencies
-    #   run: python -m pip install -r requirements_dev.txt
-    # - name: Build Client
-    #   run: python -m build
-    # - name: Test Client Package
-    #   run: bin/test-package.sh dist/*.tar.gz
     - name: Log in to the Container registry
       uses: docker/login-action@v2.1.0
       with:
@@ -52,9 +46,9 @@ jobs:
     - name: Run sanity tests
       run: |
         # Run your sanity tests here. If any command fails, the workflow will stop.
-        docker run --rm "${{ steps.tag.outputs.tag_name }}-rc" -name "${{ steps.tag.outputs.tag_name }}"
-        docker logs "${{ steps.tag.outputs.tag_name }}-rc"
-        if ! docker logs "${{ steps.tag.outputs.tag_name }}-rc" | grep -i " error"; then
+        docker run --rm "${{ steps.tag.outputs.tag_name }}-rc" -name rc
+        docker logs rc
+        if ! docker logs rc | grep -i " error"; then
             echo "No errors found in log"
         else
             echo "Errors found in log"
